### ISSUE TITLE
problem switching between sensor tabs

### ISSUE THREAD

**Issue by dan410** [sarsees/sensorEDA#2]
I’ve noticed that the app is a bit buggy when switching back and forth through the sensor tabs. For example, I have switched from IMU, to Temp, then to Mic. Then when I switch back to IMU tab it displays the temp data or some other data.

**Comment by sarsees** [comment]
Updated plotting data explicitly by tab. Though this fixes the problem of displaying the wrong plot, now there seems to be an issue with rendering the plot entirely (thought infrequently) when switching between tabs

**Comment by dan410** [comment]
Closing this issue as I think we've mostly fixed this.
